# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 232ca933557265d76ab4fdb65620f309d33b236e1c118d097de2ce38809e57cb505f0e361d0db9fd0f38af9383550c98c6fc83d8fdf599a8502ee807a24024be

test:
  secret_key_base: 21058b172182757f696cafbc013d5a124c7ea428aa84421dd58be016885f4672863de8b31b280f56fcdc3052476fa75b394d1990258bde6a80d4e47464346399

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
